# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-DOM
version:      0.003
version_from: lib/HTML/DOM.pm
installdirs:  site
requires:
    HTML::Element:                 0
    HTML::TreeBuilder:             0
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
