# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-DOM
version:      0.042
version_from: lib/HTML/DOM.pm
installdirs:  site
requires:
    Carp:                          0
    constant:                      1.03
    CSS::DOM:                      0.07
    CSS::DOM::Style:               0.05
    CSS::DOM::StyleSheetList:      0
    Date::Format:                  0
    Exporter:                      5.57
    HTML::Element:                 0
    HTML::Encoding:                0
    HTML::Parser:                  3
    HTML::Tagset:                  0
    HTML::TreeBuilder:             0
    HTTP::Headers::Util:           0
    HTTP::Message:                 1.34
    HTTP::Request:                 0
    HTTP::Request::Common:         0
    HTTP::Response:                0
    overload:                      0
    Scalar::Util:                  1.14
    strict:                        0
    Test::More:                    0
    Tie::RefHash::Weak:            0.08
    URI:                           0
    utf8:                          0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
